### ISSUE TITLE
"Class 'Nav' not found".

### ISSUE THREAD

**Issue by Kazuto** [DevMarketer/LaravelEasyNav#4]
Hey guys,

I've ran `composer require devmarketer/easynav`, added the provider and alias to config/app.php but it says `Class "Nav" not found`.﻿

I'm using Laravel 5.4.36

**Comment by jacurtis** [comment]
You will need to register the `Nav` facade and service provider as noted here: https://github.com/DevMarketer/LaravelEasyNav#2-define-the-service-provider-and-alias

This is because you are using Laravel 5.4 instead of 5.5

If you have done that (restart your server if you are running `php artisan serve` or `MAMP/WAMP/XAMP`) then remember that you also need to import the `Nav` facade if you are using it in a controller. You will need to add `use Nav;` at the top of any controller you use. THis is not necessary inside of your views though, the `Nav` facade should be available in your views as long as you have followed the instructions in step 2 (linked above).

**Comment by Kazuto** [comment]
That was a quick reply xD

I've added the facade and service provider to `config/app.php`and I just want to use it in my views, but it won't let me :O

and `php artisan vendor:publish --tag=easynav` won't create a config file for me.

`composer require devmarketer/easynav` worked, because I have a folder `vendor/devmarketer/easynav`

(https://image.ibb.co/fCsBLm/Bildschirmfoto_2017_10_20_um_17_21_43.png)

**Comment by jacurtis** [comment]
Double check that the files are in your vendor folder it should be `vendor/devmarketer/easynav`. Then maybe try the helper functions to see if they work.
https://github.com/DevMarketer/LaravelEasyNav#helper-functions

Also have you restarted any server that you are using for testing? Another idea is that you could Run `php artisan config:clear` and `php artisan cache:clear`.

The error you are getting means it can not find the EasyNav files at all i think. Otherwise you would get some sort of runtime error. This means it doesnt even know what to do when you use `Nav` which is weird. So just trying some stuff that might prevent the facade from registering in your service provider.

**Comment by jacurtis** [comment]
Also try `composer dump-autoload` in the terminal. Just to get composer to look at all the service providers and create a clean autoload file.

**Comment by Kazuto** [comment]
`php artisan config:clear` did the trick. Thanks :)

**Comment by jacurtis** [comment]
Awesome. That just clears the config cache and makes a fresh copy of it. So it looks like your app was using the cached version of the config from before you implimented the package.

This deletes that cache. If you want to cache them again run `php artisan config:cache` to cache them with the new EasyNav package in place.
