### ISSUE TITLE
is-active css class attribute of Users still when i click on Roles & Permissions..

### ISSUE THREAD

**Issue by ChileNetwork** [DevMarketer/LaravelEasyNav#7]
Hello Alex...
Users item menu is is-active class while i click on Roles & Permissions and looks like are two menu items with is-active class (backgroud-color) showing at menu vertical left ... did you note it?
So i was thinking that should be a javascript class takeing the is-active class out of <a class of everything else unless the one you are clicking ????

**Comment by jacurtis** [comment]
Is this specific to the blog tutorial or to this package?

**Comment by pankajvaghela** [comment]
This is a problem regarding accordion toggler, 
usually links are supposed to take you to other page when you click.

But when you click on According toggler, "Roles & Permission" tab here it gets activated. 
But it ain't taking you to any other page, so the other active menu item, which was active when page loaded, is staying active.

You can add javascript to  remove is-active class from all other menu items if it ain't having any submenus.
.
@jacurtis , thanks a lot *-* your tutorials are amazing

**Comment by jacurtis** [comment]
This may be a limitation of the package.  Like Pankaj mentioned, in order
to make an accordion work without changing pages, we would need to add
javascript. Which is outside of the goal of this package.  This is much
easier preformed with a few lines of js

**Comment by pankajvaghela** [comment]
You can add this just at the begining of an onclick event on accordion
```
 let alreadyActive =  document.querySelectorAll('.side-menu .is-active');
  alreadyActive.forEach(node => node.classList.toggle('is-active'));
```

**Comment by jacurtis** [comment]
So just to clarify, this is a PHP package, and it works server-side during the render of your blade view templates.

Because of that, it is simply not possible to do what was originally suggested in this issue, because the changes are being made client-side, without a new request to the server. 

This package works great for managing main navigation in your blade templates, but is not going to be an effective solution for things like client-side tabs, accordion menus, or really anything that is going to change client-side (with Javascript) without a new server request.

So @pankaj-dev provides a good solution to do this with javascript on the client side and I would reccomend doing that.

Another solution is provided in this video I created last year: https://youtu.be/VTdSW57--yM

In that video we create a no-frameworks accordian menu, and update the active class using javascript, very similar to what @pankaj-dev recommended.

I can't add this functionality to the package because it is simply outside of the scope of what is capable from a PHP, serverside package. Closing Issue #7
